apiVersion: v1
kind: ReplicationController
metadata:
  name: zipkin-cassandra
spec:
  replicas: 1
  selector:
    app: zipkin-cassandra
  template:
    metadata:
      labels:
        app: zipkin-cassandra
    spec:
      containers:
        - name: cassandra
          image: openzipkin/zipkin-cassandra-k8s:1.9.0
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SERVICE
              value: zipkin-cassandra
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command:
                - nodetool
                - decommission
      volumes:
        - name: data
          emptyDir: {}
